# Generated by Django 3.2.5 on 2021-07-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='JGomez_Bien.png', upload_to=''),
        ),
    ]
